import {assess} from '../web/lib/diagnostics.mjs';
import {captureEvidence,attentionReasons,handoff,handoffText} from '../web/lib/investigations.mjs';
import {AppError,readDoc,saveDoc,summaries,recordSummary} from './storage.mjs';
import {authenticate,authRoute,digest,randomToken,publicUser,normalizeEmail,safeEqual,passwordHash,rateLimit} from './auth.mjs';
const limited=(v,n=2000)=>typeof v==='string'?v.trim().slice(0,n):'';
const response=(b,status=200,headers={})=>new Response(JSON.stringify(b),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
async function parse(req){const text=await req.text();if(text.length>8*1024*1024)throw new AppError('Upload is too large.',413);try{return JSON.parse(text||'{}');}catch{throw new AppError('Invalid JSON request.');}}
async function config(env){return (await readDoc(env.DB,'settings'))?.body||{network:'120',networkName:'Enviro-weather/Michigan State University',delayed:60,stale:180};}
async function cacheGet(env,k){const doc=await readDoc(env.DB,'cache:'+k);return doc?{body:doc.body.data,at:doc.body.sourceAt,revision:doc.revision}:null;}
async function cacheSet(env,k,v,at){return saveDoc(env.DB,'cache:'+k,'cache',{data:v,sourceAt:at||new Date().toISOString()});}
async function networkView(env){
 const cfg=await config(env),latest=await cacheGet(env,'latest'),meta=await cacheGet(env,'metadata'),byId=new Map((latest?.body.STATION||[]).map(s=>[s.STID,s]));
 const stations=(meta?.body.STATION||[]).map(s=>assess({...s,...byId.get(s.STID)},latest?.body.UNITS||{},Date.now(),cfg));
 return {connection:{...cfg,configured:!!env.SYNOPTIC_TOKEN},fetchedAt:latest?.at||null,cacheAgeMinutes:latest?Math.floor((Date.now()-Date.parse(latest.at))/60000):null,stations:stations.map(s=>({...s,reasons:attentionReasons(s,cfg)})),units:latest?.body.UNITS||{},qcSummary:latest?.body.QC_SUMMARY||null,lastError:(await readDoc(env.DB,'refresh-error'))?.body.message||null,refreshing:false};
}
async function synoptic(env,path,params={}){
 if(!env.SYNOPTIC_TOKEN)throw new AppError('Weather data connection is not configured.',503);
 const lock=randomToken(),now=Date.now();const got=await env.DB.prepare('INSERT INTO locks(name,owner,expires) VALUES(?,?,?) ON CONFLICT(name) DO UPDATE SET owner=excluded.owner,expires=excluded.expires WHERE expires<? RETURNING owner').bind('synoptic',lock,now+60000,now).first();
 if(got?.owner!==lock)throw new AppError('Another weather request is running. Please retry in a moment.',429);
 try{const url=new URL('https://api.synopticdata.com/v2/'+path);for(const [k,v]of Object.entries({...params,token:env.SYNOPTIC_TOKEN}))url.searchParams.set(k,v);
  const res=await fetch(url,{signal:AbortSignal.timeout(45000)});if(!res.ok)throw new AppError('Weather service is unavailable. Saved observations remain available.',503);const data=await res.json();if(Number(data.SUMMARY?.RESPONSE_CODE)===403)throw new AppError('Your Synoptic account does not include this API service.',403);if(![1,2].includes(Number(data.SUMMARY?.RESPONSE_CODE)))throw new AppError('Weather service did not accept the request. Saved observations remain available.',503);return data;
 }finally{await env.DB.prepare('DELETE FROM locks WHERE name=? AND owner=?').bind('synoptic',lock).run();}
}
async function refresh(env,force=false){
 const existing=await cacheGet(env,'latest');if(!force&&existing&&Date.now()-Date.parse(existing.at)<60000)return networkView(env);
 try{const cfg=await config(env);const metadata=await synoptic(env,'stations/metadata',{network:cfg.network,complete:1,sensorvars:1});const latest=await synoptic(env,'stations/latest',{network:cfg.network,showemptystations:1,showemptyvars:1,qc:'on',qc_remove_data:'off',qc_flags:'on',qc_checks:'all',units:'metric'});if(!metadata.STATION?.length)throw new AppError('No stations were returned.',503);await cacheSet(env,'metadata',metadata);await cacheSet(env,'latest',latest);await saveDoc(env.DB,'refresh-error','settings',{message:null});return networkView(env);
 }catch(e){await saveDoc(env.DB,'refresh-error','settings',{message:e.status===429?'Another weather request was running at refresh time.':e instanceof AppError?e.message:'Weather service is unavailable. Saved observations remain available.'});throw e;}
}
async function evidence(env,b,stationId){const network=await networkView(env),histories=new Map();for(const id of [stationId,...b.comparisonIds||[]])histories.set(id,await cacheGet(env,`history:${id}:${b.hours||24}`));const supplemental={};for(const service of ['precip','statistics','qcsegments']){const product=await cacheGet(env,`product:${service}:${stationId}:${b.hours||24}`);if(product)supplemental[service]={fetchedAt:product.at,data:product.body};}return {...captureEvidence({network,stationId,hours:b.hours||24,variable:b.variable||'air_temp',comparisonIds:b.comparisonIds||[],getHistory:(id)=>histories.get(id)}),supplemental};}
async function saveRecord(env,r,expected){r.updated=new Date().toISOString();return saveDoc(env.DB,'record:'+r.id,r.caseType==='investigation'?'investigation':r.kind,r,recordSummary(r),expected);}
async function route(req,env){
 const url=new URL(req.url),path=url.pathname.replace(/^\/api/,'')||'/',method=req.method;
 if(path==='/health')return response({ok:true,service:'Enviroweather Fleet',version:'1.0.0'});
 if(path.startsWith('/auth/')&&path!='/auth/me'&&path!='/auth/logout'&&path!='/auth/password')return response(await authRoute(req,env,path,method==='POST'?await parse(req):{}));
 if(path==='/migration'&&method==='POST'){
  if(!env.MIGRATION_TOKEN||!safeEqual(req.headers.get('X-Migration-Token')||'',env.MIGRATION_TOKEN))throw new AppError('Sign in to continue.',401);
  const b=await parse(req);for(const [key,value]of Object.entries(b.cache||{}))await cacheSet(env,key,value.body||value,value.at);
  let records=0,visits=0;for(const original of b.records||[]){const r={...original};if(await readDoc(env.DB,'record:'+r.id))continue;await saveRecord(env,r);records++;}
  for(const v of b.visits||[]){const clean={...v,photos:[],sharedAt:new Date().toISOString(),sharedBy:'EJ',attachmentNote:'Photos remain in the iPad notebook; completed PDFs are shared in Teams.'};await saveDoc(env.DB,'visit:'+v.id,'visit',clean,recordSummary(clean));visits++;}
  if(b.refresh)await refresh(env,true);return response({records,visits,cache:Object.keys(b.cache||{}).length});
 }
 const user=await authenticate(req,env);if(!user)throw new AppError('Sign in to continue.',401);
 if(path==='/auth/me')return response(publicUser(user));
 if(path==='/auth/logout'&&method==='POST'){await env.DB.prepare('DELETE FROM sessions WHERE hash=?').bind(await digest(req.headers.get('Authorization').slice(7))).run();return response({ok:true});}
 if(path==='/auth/password'&&method==='POST'){const b=await parse(req);await rateLimit(env.DB,'password:'+user.id);if(typeof b.currentPassword!=='string'||!safeEqual(await passwordHash(b.currentPassword,user.salt),user.password_hash))throw new AppError('Current password is incorrect.',403);if(typeof b.password!=='string'||b.password.length<14||b.password.length>256)throw new AppError('Use at least 14 characters.');const salt=randomToken(),hash=await passwordHash(b.password,salt);await env.DB.batch([env.DB.prepare('UPDATE users SET password_hash=?,salt=? WHERE id=?').bind(hash,salt,user.id),env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(user.id)]);return response({ok:true});}
 if(!['GET','HEAD'].includes(method)&&user.role==='viewer')throw new AppError('Your account has view-only access.',403);
 if(path==='/team'&&method==='GET'){if(user.role!=='owner')throw new AppError('Only the owner can manage team access.',403);const {results}=await env.DB.prepare('SELECT id,email,name,role,active FROM users ORDER BY created').all();return response({users:results});}
 if(path==='/team/invites'&&method==='POST'){if(user.role!=='owner')throw new AppError('Only the owner can invite teammates.',403);const b=await parse(req),email=normalizeEmail(b.email);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!['editor','viewer'].includes(b.role))throw new AppError('Enter an email and access level.');const token=randomToken();await env.DB.prepare('INSERT INTO invites(hash,email,role,expires) VALUES(?,?,?,?)').bind(await digest(token),email,b.role,Date.now()+7*86400000).run();return response({url:'https://atolldb.com/#invite='+token,email,role:b.role});}
 if(path.startsWith('/team/users/')&&method==='PATCH'){if(user.role!=='owner')throw new AppError('Only the owner can manage access.',403);const id=path.split('/').at(-1),b=await parse(req);if(id===user.id)throw new AppError('The owner account must remain active.');await env.DB.prepare('UPDATE users SET active=? WHERE id=? AND role<>?').bind(b.active?1:0,id,'owner').run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(id).run();return response({ok:true});}
 if(path==='/state'&&method==='GET')return response({...await networkView(env),records:await summaries(env.DB,['issue','bench','investigation']),user:publicUser(user)});
 if(path==='/refresh'&&method==='POST')return response(await refresh(env));
 if(path==='/thresholds'&&method==='POST'){const b=await parse(req);if(!Number.isInteger(b.delayed)||!Number.isInteger(b.stale)||b.delayed<5||b.stale<=b.delayed||b.stale>10080)throw new AppError('Use whole minutes: delayed ≥5, stale greater than delayed and ≤10080.');await saveDoc(env.DB,'settings','settings',{...await config(env),delayed:b.delayed,stale:b.stale});return response(await config(env));}
 if(path==='/history'&&method==='GET'){const id=url.searchParams.get('station'),hours=Number(url.searchParams.get('hours')||24);if(![24,72,168].includes(hours))throw new AppError('Choose 24 hours, 3 days, or 7 days.');if(!(await networkView(env)).stations.some(s=>s.id===id))throw new AppError('Unknown station.');const key=`history:${id}:${hours}`,cached=await cacheGet(env,key);if(cached&&Date.now()-Date.parse(cached.at)<600000)return response({...cached.body,fetchedAt:cached.at,cached:true});const data=await synoptic(env,'stations/timeseries',{stid:id,recent:hours*60,units:'metric',qc:'on',qc_remove_data:'off',qc_flags:'on',qc_checks:'all'});await cacheSet(env,key,data);return response({...data,fetchedAt:new Date().toISOString(),cached:false});}
 if(path==='/products'&&method==='GET'){const id=url.searchParams.get('station'),hours=Number(url.searchParams.get('hours')||24),service=url.searchParams.get('service');if(![24,72,168].includes(hours)||!['precip','statistics','qcsegments'].includes(service))throw new AppError('Choose a supported product and window.');if(!(await networkView(env)).stations.some(s=>s.id===id))throw new AppError('Unknown station.');const key=`product:${service}:${id}:${hours}`,cached=await cacheGet(env,key);if(cached&&Date.now()-Date.parse(cached.at)<600000)return response({...cached.body,fetchedAt:cached.at,cached:true,service});const params=service==='statistics'?{stid:id,recent:Math.ceil(hours/24),period:'day',vars:'air_temp,relative_humidity,wind_speed,solar_radiation',statistic:'all',units:'metric'}:service==='precip'?{stid:id,recent:hours*60,pmode:'totals',units:'metric',showemptystations:1}:{stid:id,recent:hours*60,qc_checks:'all',showemptystations:1};const data=await synoptic(env,'stations/'+service,params);await cacheSet(env,key,data);return response({...data,fetchedAt:new Date().toISOString(),cached:false,service});}
 if(path==='/investigations'&&method==='POST'){const b=await parse(req),station=limited(b.station,100),title=limited(b.title,200),notes=limited(b.notes,10000);if(!title||!notes)throw new AppError('Enter a title and investigation notes.');const existing=(await summaries(env.DB,['investigation'])).find(r=>r.station===station&&r.status==='open');if(existing)return response({...((await readDoc(env.DB,'record:'+existing.id)).body),existing:true});const now=new Date().toISOString(),r={id:crypto.randomUUID(),kind:'issue',caseType:'investigation',title,notes,station,status:'open',source:'Saved Synoptic investigation evidence',plannedChecks:limited(b.plannedChecks,5000),evidence:[await evidence(env,b,station)],activity:[{at:now,action:'Investigation created',actor:user.name,status:'open'}],created:now,updated:now};await saveRecord(env,r);return response(r,201);}
 const match=path.match(/^\/records\/([^/]+)(?:\/(evidence|handoff))?$/);
 if(match){const doc=await readDoc(env.DB,'record:'+match[1]);if(!doc)throw new AppError('Record not found.',404);const r=doc.body,action=match[2];
  if(action==='handoff'&&method==='GET'){if(url.searchParams.get('format')==='text')return new Response(handoffText(r),{headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}});return response(handoff(r));}
  if(action==='evidence'&&method==='POST'){if(r.caseType!=='investigation')throw new AppError('Choose an investigation.');if(r.evidence.length>=50)throw new AppError('Export this case and start a follow-up case.');r.evidence.push(await evidence(env,await parse(req),r.station));r.activity.push({at:new Date().toISOString(),action:'Evidence snapshot added',actor:user.name,status:r.status});await saveRecord(env,r,doc.revision);return response(r,201);}
  if(!action&&method==='GET')return response({...r,_revision:doc.revision});
  if(!action&&method==='PATCH'){const b=await parse(req);if(!b.revision||b.revision!==doc.revision)throw new AppError('Someone updated this record. Your entries are still open; reopen the record before saving.',409);if(b.status!==undefined&&!['open','resolved'].includes(b.status))throw new AppError('Invalid status.');if(r.caseType==='investigation'&&b.station!==undefined&&b.station!==r.station)throw new AppError('Evidence stays attached to its original station.');for(const [key,max]of Object.entries({title:200,station:100,notes:10000,equipment:500,program:500,expected:3000,observed:3000,plannedChecks:5000}))if(b[key]!==undefined)r[key]=limited(b[key],max);if(!r.title)throw new AppError('Enter a title.');if(b.status!==undefined)r.status=b.status;if(b.outcome!==undefined){if(!['pass','fail','inconclusive'].includes(b.outcome))throw new AppError('Invalid conclusion.');r.outcome=b.outcome;}r.activity=[...r.activity||[],{at:new Date().toISOString(),actor:user.name,action:b.status?(b.status==='open'?'Case reopened':'Case resolved'):'Notes updated',status:r.status}];await saveRecord(env,r,doc.revision);return response({ok:true});}
 }
 if(path==='/records'&&method==='POST'){const b=await parse(req);if(!['issue','bench'].includes(b.kind)||!limited(b.title,200))throw new AppError('Enter a title and record type.');const now=new Date().toISOString(),r={id:crypto.randomUUID(),kind:b.kind,title:limited(b.title,200),station:limited(b.station,100),notes:limited(b.notes,10000),status:'open',source:limited(b.source,500)||'Manually entered',equipment:limited(b.equipment,500),program:limited(b.program,500),expected:limited(b.expected,3000),observed:limited(b.observed,3000),outcome:['pass','fail','inconclusive'].includes(b.outcome)?b.outcome:'inconclusive',created:now,activity:[{at:now,actor:user.name,action:'Record created'}]};await saveRecord(env,r);return response(r,201);}
 if(path==='/visits'&&method==='GET')return response(await summaries(env.DB,['visit']));
 if(path.startsWith('/visits/')&&method==='GET'){const doc=await readDoc(env.DB,'visit:'+path.split('/').at(-1));if(!doc)throw new AppError('Visit not found.',404);return response(doc.body);}
 if(path==='/visits'&&method==='POST'){const b=await parse(req),v=b.visit;if(!v||typeof v.id!=='string'||!v.fields?.siteName||!v.fields?.date||v.status!=='complete')throw new AppError('Complete the station visit before publishing.');const previous=await readDoc(env.DB,'visit:'+v.id);const clean={...v,photos:[],sharedAt:new Date().toISOString(),sharedBy:user.name,attachmentNote:'Photos stay in the local notebook. Share the completed PDF in Teams.'};await saveDoc(env.DB,'visit:'+v.id,'visit',clean,recordSummary(clean),previous?.revision);return response({ok:true,sharedAt:clean.sharedAt});}
 if(path==='/export'&&method==='GET'){const records=[];for(const summary of await summaries(env.DB,['issue','bench','investigation']))records.push((await readDoc(env.DB,'record:'+summary.id)).body);const visits=[];for(const summary of await summaries(env.DB,['visit']))visits.push((await readDoc(env.DB,'visit:'+summary.id)).body);return response({schemaVersion:2,exportedAt:new Date().toISOString(),...await networkView(env),records,visits});}
 throw new AppError('Endpoint not found.',404);
}
export default {
 async fetch(req,env){
  const origin=req.headers.get('Origin'),allowed=(env.ALLOWED_ORIGINS||'').split(','),cors=origin&&allowed.includes(origin)?{'Access-Control-Allow-Origin':origin,'Vary':'Origin'}:{};
  const headers={...cors,'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Cache-Control':'no-store'};
  if(origin&&!allowed.includes(origin))return response({error:'This origin is not allowed.'},403,headers);
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{...headers,'Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Access-Control-Allow-Headers':'Authorization,Content-Type','Access-Control-Max-Age':'600'}});
  try{const res=await route(req,env);for(const [key,v]of Object.entries(headers))res.headers.set(key,v);return res;}catch(e){const status=e.status||500;if(status===500)console.error('Request failed:',String(e.message).replaceAll(env.SYNOPTIC_TOKEN||'__unset__','[redacted]').slice(0,500));return response({error:status===500?'The service could not complete this request. Your entries have not been discarded. Please retry.':e.message},status,headers);}
 },
 async scheduled(controller,env,ctx){ctx.waitUntil((async()=>{try{await refresh(env,true);}catch{}await env.DB.prepare('DELETE FROM sessions WHERE expires<?').bind(Date.now()).run();await env.DB.prepare('DELETE FROM attempts WHERE expires<?').bind(Date.now()).run();})());}
};
