import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../worker.mjs';
import {readDoc,saveDoc} from '../storage.mjs';
function database(){const sql=new DatabaseSync(':memory:');for(const name of ['0001_fleet.sql','0002_credential_generation.sql','0003_compact_visit_summaries.sql','0004_invalid_legacy_visit_ids.sql'])sql.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8'));const db={prepare(query){let values=[];const stmt=sql.prepare(query);return {bind(...v){values=v;return this;},async first(){return stmt.get(...values)||null;},async all(){return {results:stmt.all(...values)};},async run(){const r=stmt.run(...values);return {meta:{changes:Number(r.changes)}};}};},async batch(stmts){sql.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sql.exec('COMMIT');return r;}catch(e){sql.exec('ROLLBACK');throw e;}}};return db;}
const env={DB:database(),OWNER_EMAIL:'owner@example.com',BOOTSTRAP_TOKEN:'bootstrap-test',MIGRATION_TOKEN:'migration-test',ALLOWED_ORIGINS:'https://atolldb.com'};
async function call(path,{token,method='GET',body,origin,...headers}={}){return worker.fetch(new Request('https://fleet.test/api/'+path,{method,headers:{...(origin?{Origin:origin}:{}),...(token?{Authorization:'Bearer '+token}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})}),env);}
let owner,viewer;
test('private workspace and CORS reject unauthorized requests',async()=>{assert.equal((await call('state')).status,401);assert.equal((await call('health',{origin:'https://evil.example'})).status,403);assert.equal((await call('health',{origin:'https://atolldb.com'})).headers.get('Access-Control-Allow-Origin'),'https://atolldb.com');});
test('account setup requires a secret; invitations cannot elevate privileges',async()=>{assert.equal((await call('auth/register',{method:'POST',body:{name:'Owner',email:env.OWNER_EMAIL,password:'test-password-only-123',token:'bad'}})).status,403);let r=await call('auth/register',{method:'POST',body:{name:'Owner',email:env.OWNER_EMAIL,password:'test-password-only-123',token:env.BOOTSTRAP_TOKEN}});assert.equal(r.status,200);owner=(await r.json()).token;assert.equal((await call('auth/register',{method:'POST',body:{name:'Other',email:'other@example.com',password:'test-password-only-123',token:env.BOOTSTRAP_TOKEN}})).status,403);r=await call('team/invites',{token:owner,method:'POST',body:{email:'viewer@example.com',role:'viewer'}});const invite=new URL((await r.json()).url).hash.split('=')[1];r=await call('auth/register',{method:'POST',body:{name:'Viewer',email:'viewer@example.com',password:'test-password-only-123',token:invite,role:'owner'}});assert.equal(r.status,200);const u=await r.json();viewer=u.token;assert.equal(u.user.role,'viewer');assert.equal((await call('records',{token:viewer,method:'POST',body:{kind:'issue',title:'blocked'}})).status,403);assert.equal((await call('team',{token:viewer})).status,403);});
test('large evidence is durable and stale revisions cannot overwrite newer entries',async()=>{const body={notes:'α'.repeat(800000),status:'open'};const rev=await saveDoc(env.DB,'large-test','test',body);assert.deepEqual((await readDoc(env.DB,'large-test')).body,body);const next=await saveDoc(env.DB,'large-test','test',{notes:'newer'}, {},rev);await assert.rejects(saveDoc(env.DB,'large-test','test',{notes:'stale'}, {},rev),e=>e.status===409);assert.equal((await readDoc(env.DB,'large-test')).revision,next);assert.equal((await readDoc(env.DB,'large-test')).body.notes,'newer');});
test('records preserve evidence; revisions and exports are private',async()=>{let r=await call('records',{token:owner,method:'POST',body:{kind:'issue',title:'Test case',notes:'Original'}});assert.equal(r.status,201);const id=(await r.json()).id;r=await call('records/'+id,{token:owner});const before=await r.json();assert.equal((await call('records/'+id,{token:owner,method:'PATCH',body:{revision:before._revision,notes:'Updated',evidence:['fake']}})).status,200);assert.equal((await call('records/'+id,{token:owner,method:'PATCH',body:{revision:before._revision,notes:'Stale'}})).status,409);const after=await (await call('records/'+id,{token:owner})).json();assert.equal(after.notes,'Updated');assert.equal(after.evidence,undefined);assert.equal((await call('export')).status,401);assert.equal((await call('export',{token:viewer})).status,200);});
test('sharing completed visits strips local photo payloads; disabling a teammate revokes sessions',async()=>{const visit={schemaVersion:1,updated:new Date().toISOString(),sources:{},history:[],id:'visit-test',fields:{siteName:'Test station',date:'2026-10-05'},status:'complete',photos:[{dataUrl:'data:image/jpeg;base64,secret'}]};assert.equal((await call('visits',{token:owner,method:'POST',body:{visit}})).status,200);const saved=await (await call('visits/visit-test',{token:viewer})).json();assert.deepEqual(saved.photos,[]);const users=await (await call('team',{token:owner})).json();const id=users.users.find(u=>u.role==='viewer').id;assert.equal((await call('team/users/'+id,{token:owner,method:'PATCH',body:{active:false}})).status,200);assert.equal((await call('state',{token:viewer})).status,401);});
test('password changes require the old password and revoke all existing sessions',async()=>{assert.equal((await call('auth/password',{token:owner,method:'POST',body:{currentPassword:'wrong',password:'new-test-password-123'}})).status,403);assert.equal((await call('auth/password',{token:owner,method:'POST',body:{currentPassword:'test-password-only-123',password:'new-test-password-123'}})).status,200);assert.equal((await call('state',{token:owner})).status,401);assert.equal((await call('auth/login',{method:'POST',body:{email:env.OWNER_EMAIL,password:'test-password-only-123'}})).status,401);assert.equal((await call('auth/login',{method:'POST',body:{email:env.OWNER_EMAIL,password:'new-test-password-123'}})).status,200);});
