import {test} from 'node:test';
import assert from 'node:assert/strict';
import {latestReport,referenceTracker,band,nearby} from '../../web/lib/reference.mjs';
const now=Date.parse('2026-10-05T16:00:00Z'),base=now-7200000;
const point=(i,v)=>({t:base+i*600000,v,flagged:false});
function target(offset=0){return {unit:'Celsius',points:Array.from({length:13},(_,i)=>point(i,10+i+offset))};}
function peers(){return [-0.2,0,0.2].map((offset,j)=>({...target(offset),station:{id:'N'+j,name:'Synthetic '+j,distance:10+j}}));}
function station(id,value,time=now){return {id,name:'Synthetic '+id,lat:44,lon:-85+Number(id.slice(1)||0)*0.01,archiveStatus:'ACTIVE',fields:[{key:'air_temp_value_1',variable:'air_temp',value,time:new Date(time).toISOString(),unit:'Celsius',qc:[],derived:false}]};}
test('reference bands resist one extreme neighbor and have a provisional tolerance floor',()=>{const b=band([10,10.1,10.2,40],3);assert.equal(b.tolerance,3);assert.equal(b.median,10.149999999999999);assert.ok(b.high<14);assert.equal(b.max,40);});
test('shared weather changes stay inside the reference band',()=>{const r=referenceTracker(target(),peers(),'air_temp',{},now);assert.equal(r.summary.evaluated,13);assert.equal(r.summary.outside,0);assert.equal(r.weather.kind,'shared-change');assert.equal(r.weather.referenceChange,6);});
test('persistent offsets remain reviewable even when the station follows the regional trend',()=>{const r=referenceTracker(target(10),peers(),'air_temp',{},now);assert.equal(r.summary.outside,13);assert.equal(r.summary.persistent,true);assert.equal(r.weather.kind,'shared-change-offset');assert.equal(r.summary.medianOffset,10);});
test('a station-only step is distinct from a shared weather change',()=>{const t=target();for(const p of t.points.slice(7))p.v+=12;const r=referenceTracker(t,peers(),'air_temp',{},now);assert.equal(r.weather.kind,'isolated-change');assert.ok(r.weather.targetChange>r.weather.referenceChange);});
test('flagged, misaligned and wrong-unit peers cannot create a reference',()=>{const p=peers();p[0].points=p[0].points.map(q=>({...q,flagged:true}));p[1].unit='Fahrenheit';p[2].points=p[2].points.map(q=>({...q,t:q.t+360000}));const r=referenceTracker(target(),p,'air_temp',{},now);assert.equal(r.summary.evaluated,0);assert.equal(r.weather.kind,'unavailable');assert.equal(r.summary.outsidePercent,null);});
test('flagged target and unknown units remain excluded or unscorable rather than pass',()=>{const t=target();t.points.at(-1).flagged=true;const r=referenceTracker(t,peers(),'air_temp',{},now);assert.equal(r.latest.status,'excluded');assert.equal(r.summary.evaluated,12);const missing=referenceTracker({...target(),unit:null},peers(),'air_temp',{},now);assert.equal(missing.summary.evaluated,0);});
test('changing reference membership does not manufacture a weather trend',()=>{const t={unit:'Celsius',points:[point(0,10),point(6,10)]};const p=[...['a','b','c'].map(id=>({unit:'Celsius',station:{id},points:[point(0,10)]})),...['d','e','f'].map(id=>({unit:'Celsius',station:{id},points:[point(6,20)]}))];const r=referenceTracker(t,p,'air_temp',{},now);assert.equal(r.summary.evaluated,2);assert.equal(r.weather.kind,'unavailable');assert.match(r.weather.message,/same neighbors/);});
test('snapshot reports compare fresh aligned values and preserve missing-reference distinctions',()=>{const stations=[station('N0',24),station('N1',10),station('N2',10.1),station('N3',9.9)],r=latestReport({stations,fetchedAt:new Date(now).toISOString()},{},now);const target=r.rows.find(r=>r.stationId==='N0'&&r.variable==='air_temp');assert.equal(target.status,'review');assert.equal(target.neighbors.length,3);assert.equal(target.delta,14);assert.equal(r.rows.find(r=>r.stationId==='N0'&&r.variable==='wind_speed').status,'insufficient');});
test('stale channels and failed QC never become healthy reference rows',()=>{const stations=[station('N0',12,now-7200000),station('N1',12),station('N2',12),station('N3',12)];stations[1].fields[0].qcStatus='failed';const r=latestReport({stations},{},now);assert.equal(r.rows.find(r=>r.stationId==='N0'&&r.variable==='air_temp').status,'excluded');assert.equal(r.rows.find(r=>r.stationId==='N1'&&r.variable==='air_temp').status,'excluded');assert.equal(r.summary.inRange,0);});
test('reference selection excludes missing coordinates and inactive stations',()=>{const t=station('N0',10),a=station('N1',10),b={...station('N2',10),lat:null},c={...station('N3',10),archiveStatus:'INACTIVE'};assert.deepEqual(nearby(t,[t,a,b,c]).map(s=>s.id),['N1']);});
test('co-located instruments cannot count as independent nearby reference sites',()=>{const t=station('N0',10),same={...t,id:'same-site'},a=station('N1',10),duplicate={...a,id:'second-height'},b=station('N2',10);assert.deepEqual(nearby(t,[t,same,a,duplicate,b]).map(s=>s.id),['N1','N2']);});
