import {depthTemps,depthMoistures} from './field-core.mjs?v=cleanup-1';
const f=(key,label,unit='',type='text')=>`<label class="field">${label}${unit?`<div class="unit-input"><input name="${key}" inputmode="decimal"><span>${unit}</span></div>`:`<input name="${key}" type="${type}">`}</label>`;
const c=(key,label,main=false)=>`<label class="check ${main?'main-check':''}"><input type="checkbox" name="${key}">${label}</label>`;
const r=(key,title,options)=>`<fieldset><legend>${title}</legend><div class="choices">${options.map(([value,label])=>`<label><input type="radio" name="${key}" value="${value}">${label}</label>`).join('')}</div></fieldset>`;
const text=(key,title,rows)=>`<label class="field">${title}<textarea name="${key}" rows="${rows}"></textarea></label>`;
const photoSection=(phase,title,description)=>`<section id="${phase}Photos" class="photo-section"><div class="photo-heading"><div><h2>${title}</h2><p class="small">${description}</p></div><span id="${phase}PhotoCount" class="photo-count">No photos yet</span></div><div class="photo-actions"><label class="file-button primary">Take ${phase} photo<input type="file" accept="image/*" capture="environment" data-photo-phase="${phase}" aria-label="Take ${phase} photo"></label><label class="file-button quiet">Add from Photos / Files<input type="file" accept="image/*" multiple data-photo-phase="${phase}" aria-label="Add ${phase} photos"></label></div><div id="${phase}PhotoStatus" class="small" role="status"></div><div id="${phase}PhotoGrid" class="photo-grid"></div></section>`;
const row=html=>`<div class="work-row">${html}</div>`;
export function renderForm(){return `
<section id="visit" class="visit-grid"><div><div class="two">${f('siteName','Site Name')}${f('siteId','ID')}</div>${f('date','Date','','date')}<div class="two">${f('timeIn','Time In','','time')}${f('timeOut','Time Out','','time')}</div>${f('technicians','Technician(s) on Site')}</div><div>${f('ticket','Ticket Number: (FS#)')}${r('maintenance','Maintenance Mode Activated:',[['yes','Yes'],['no','No']])}<div class="two">${f('maintenanceOn','If Yes, Time On','','time')}${f('maintenanceOff','Time Off','','time')}</div><p class="small">Record the maintenance interval you set in LoggerLink.</p></div></section>
<section id="observations">${text('observations','Initial Observations',3)}</section>
${photoSection('arrival','Arrival photos','Photograph the station as you find it, before starting work.')}
<section id="work"><h2>Work Completed</h2>
${row(c('grassDone','Trimmed Grass / Weeds (Weed-Whacked)',true)+f('grassNotes','Notes'))}
${row(c('windDone','Wind Speed & Direction',true)+`<div class="reading-grid">${f('windSpeed','Speed','m/s')}${f('windDirection','Direction','°')}${c('windVerified','Verified with Kestrel & Compass')}</div>`+f('windOther','Other Height Values'))}
${row(c('airDone','AT/RH',true)+`<div class="reading-grid">${f('airTemp','Air temperature','°C')}${f('humidity','Relative humidity','%')}${f('airModel','Sensor Model')}</div>`+c('airInspected','Shield Cleaned, Chip Inspected, Verified by Kestrel')+f('airOther','Other Height Values'))}
${row(c('solarDone','Pyranometer',true)+`<div class="reading-grid">${f('solarOpen','Open Value','W/m²')}${f('solarCovered','Covered Value','W/m²')}${c('solarCleaned','Cleaned')}</div>`+r('sky','Sky',[['full sun','Full sun'],['mod. sun','Mod. sun'],['pt. sun','Pt. sun'],['pt. cloudy','Pt. cloudy'],['mod. clouds','Mod. clouds'],['cloudy','Cloudy']]))}
${row(c('lws0Done','LWS0',true)+`<div class="reading-grid">${f('lws0Wet','Wet','mV')}${f('lws0Dry','Dry','mV')}${c('lws0Cleaned','Cleaned')}</div>`)}
${row(c('lws1Done','(Canopy) C_LWS1',true)+`<div class="reading-grid">${f('lws1Wet','Wet','mV')}${f('lws1Dry','Dry','mV')}${c('lws1Cleaned','Cleaned')}</div>`)}
${row(c('rainDone','Tipping Bucket',true)+`<div class="reading-grid">${f('rain1','1× Tip Reading','mm')}${f('rain3','3× Tip Reading','mm')}<div>${c('rainLeveled','Leveled')}${c('rainCleaned','Cleaned')}</div></div>`)}
</section>
<section id="soil">${c('soilDone','Soil Temp/Moisture',true)}<div class="soil-layout"><div><div class="soil-header"><span>Depth</span><span>Temperature · °C</span><span>Moisture · %</span></div>${[5,10,20,50,100,30,60].map(d=>`<div class="soil-row"><span>${d} cm</span>${depthTemps.includes(d)?`<input name="soilTemp${d}" inputmode="decimal" aria-label="Soil temperature ${d} cm">`:'<span></span>'}${depthMoistures.includes(d)?`<input name="soilMoisture${d}" inputmode="decimal" aria-label="Soil moisture ${d} cm">`:'<span></span>'}</div>`).join('')}</div>${text('additionalSensors','Additional Sensors',7)}</div></section>
<section id="power"><h2>Power & Battery</h2>${row(c('powerDone','Power Source',true)+r('powerSource','',[['solar','Solar'],['ac-dc','AC-DC']]))}${row(c('panelDone','Solar Panel Cleaned & Voltage Checked',true)+f('panelVoltage','Voltage','V'))}${row(c('batteryDone','Battery Voltage',true)+f('batteryVoltage','Voltage','V'))}${row(c('batteryBoxDone','Battery Box Condition & Battery Type',true)+`<div class="reading-grid">${f('batteryCondition','Condition')}${f('batteryType','Battery Type')}${f('batteryAh','Capacity','Ah')}</div>`)}${r('sensorReplaced','Sensor Replaced?',[['yes','Yes'],['no','No']])}</section>
<section id="notes">${text('notes','Additional Notes',6)}${c('picturesTaken','Remember to Take Pictures!')}</section>
${photoSection('departure','Departure photos','Photograph the station after completing work, before leaving.')}
${photoSection('additional','Additional photos','Document damage, repairs, sensor changes, or anything else during your visit.')}
<section id="provenance" hidden><h2>Imported Reading Sources</h2><div id="sourceList"></div></section>`;}
