import { validateGraph } from "./validate.js";
import { generateSql } from "./generateSql.js";
import { generateRlsPolicies } from "./generateRls.js";
import { generateRouteContracts } from "./generateRouteContracts.js";
import { generateFunctionStubs } from "./generateFunctionStubs.js";
import { generateAgentGatewayPolicy } from "./generateAgentGatewayPolicy.js";
import { generatePolicyTests, runPolicyTests } from "./generatePolicyTests.js";
import { generateDeployPlan } from "./generateDeployPlan.js";
import { evaluateAccess } from "./evaluateAccess.js";
import { introspectSql } from "./introspect.js";
import { REQUIRED_ARTIFACTS } from "./helpers.js";

export { validateGraph } from "./validate.js";
export { generateSql } from "./generateSql.js";
export { generateRlsPolicies } from "./generateRls.js";
export { generateRouteContracts } from "./generateRouteContracts.js";
export { generateFunctionStubs } from "./generateFunctionStubs.js";
export { generateAgentGatewayPolicy } from "./generateAgentGatewayPolicy.js";
export { generatePolicyTests, runPolicyTests } from "./generatePolicyTests.js";
export { generateDeployPlan } from "./generateDeployPlan.js";
export { evaluateAccess } from "./evaluateAccess.js";
export { introspectSql } from "./introspect.js";
export { REQUIRED_ARTIFACTS } from "./helpers.js";

export function compileGraph(graph) {
  const validation = validateGraph(graph);
  if (!validation.valid) {
    const error = new Error(`Invalid Baseplane graph:\n${validation.errors.join("\n")}`);
    error.validation = validation;
    throw error;
  }

  return {
    "baseplane.json": `${JSON.stringify(graph, null, 2)}\n`,
    "schema.sql": generateSql(graph),
    "rls_policies.sql": generateRlsPolicies(graph),
    "route_contracts.md": generateRouteContracts(graph),
    "function_stubs.md": generateFunctionStubs(graph),
    "agent_gateway_policy.json": `${JSON.stringify(generateAgentGatewayPolicy(graph), null, 2)}\n`,
    "policy_tests.json": `${JSON.stringify(generatePolicyTests(graph), null, 2)}\n`,
    "deploy_plan.md": generateDeployPlan(graph),
    "README.md": generateReadme(graph)
  };
}

export function assertRequiredArtifacts(artifacts) {
  return REQUIRED_ARTIFACTS.filter((name) => !Object.prototype.hasOwnProperty.call(artifacts, name));
}

function generateReadme(graph) {
  return `# ${graph.app.name}

Generated by Baseplane.

${graph.app.description}

## Files

- baseplane.json: graph source of truth
- schema.sql: Postgres table sketch
- rls_policies.sql: policy sketch
- route_contracts.md: route/API contracts
- function_stubs.md: function/API contracts
- agent_gateway_policy.json: AI-agent permission model
- policy_tests.json: generated policy simulator cases
- deploy_plan.md: dry-run deployment plan

## Boundary

This package does not contain production credentials or customer data.
Review generated SQL and policies before applying anything to production.
`;
}
