import {API_BASE} from './config.js';
let token='';try{token=sessionStorage.getItem('fleet-session')||'';}catch{}
export const hasSession=()=>!!token;
export function setSession(value){token=value;try{if(value)sessionStorage.setItem('fleet-session',value);else sessionStorage.removeItem('fleet-session');}catch{}}
export async function request(path,options={}){
 const res=await fetch(API_BASE+'/'+path.replace(/^\//,''),{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...options.headers},signal:options.signal||AbortSignal.timeout(60000)});
 const data=await res.json();if(!res.ok){const error=new Error(data.error||'Request failed.');error.status=res.status;if(res.status===401&&!path.startsWith('auth/'))window.dispatchEvent(new CustomEvent('fleet-auth-required'));throw error;}return data;
}
export async function downloadFromAPI(path,filename){const res=await fetch(API_BASE+'/'+path.replace(/^\//,''),{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(60000)});if(!res.ok){let b={};try{b=await res.json();}catch{}throw new Error(b.error||'Unable to download.');}const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
export function showAuth(root,onSuccess){
 const fragment=new URLSearchParams(location.hash.slice(1)),invite=fragment.get('invite'),setup=fragment.get('setup'),register=!!(invite||setup),inviteToken=invite||setup||'';
 if(inviteToken)history.replaceState(null,'',location.pathname);
 root.innerHTML=`<div class="auth-layout"><section class="auth-context"><img src="/field-notes/enviroweather-logo.png" alt="Enviroweather" width="64" height="64"><h1>Enviroweather Fleet</h1><p>Station diagnostics, investigations, and fieldwork.</p><div class="auth-capabilities"><span>Michigan radar & station readings</span><span>Saved evidence & maintenance history</span><span>Field Notes & logger testing</span></div><a href="/field-notes/">Open your offline field notebook</a></section><section class="auth-panel"><div class="eyebrow">TEAM WORKSPACE</div><h2>${register?'Create your account':'Sign in'}</h2><p>${register?'Choose a password for your Enviroweather account.':'Use your Enviroweather Fleet email and password.'}</p><form id="auth-form">${register?'<label for="auth-name">Name</label><input id="auth-name" name="name" required autocomplete="name" maxlength="100">':''}<label for="auth-email">Email</label><input id="auth-email" name="email" type="email" required autocomplete="username" ${setup?'value="howeej2255@gmail.com"':''}><label for="auth-password">Password</label><input id="auth-password" name="password" type="password" required autocomplete="${register?'new-password':'current-password'}" ${register?'minlength="14"':''} maxlength="256">${register?'<p class="footnote">Use at least 14 characters.</p>':''}<p id="auth-error" class="auth-error" role="alert"></p><button class="primary" type="submit">${register?'Create account':'Sign in'}</button></form><p class="footnote">${register?'Your invitation determines your team access.':'New here? Ask the workspace owner for an invitation link.'}</p></section></div>`;
 root.querySelector('#auth-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button'),err=root.querySelector('#auth-error');b.disabled=true;err.textContent='';try{const values=Object.fromEntries(new FormData(e.target));const r=await request('auth/'+(register?'register':'login'),{method:'POST',body:JSON.stringify({...values,token:inviteToken})});setSession(r.token);await onSuccess(r.user);}catch(error){err.textContent=error.message;}finally{b.disabled=false;}};
}
